In [ ]:
!pip install ydata_profiling

In [2]:
import pandas as pd
from ydata_profiling import ProfileReport

/var/folders/18/2jngcg0x5csd3tyb3xj47rrm0000gn/T/ipykernel_55639/2829373970.py:2: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

In [3]:
from pathlib import Path

In [4]:
df_epa = pd.read_csv("../../data/interim/EPA_joined.csv", sep=",")

/var/folders/18/2jngcg0x5csd3tyb3xj47rrm0000gn/T/ipykernel_55639/681696753.py:1: DtypeWarning: Columns (12,13,14,15,17,20,22,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,75,76,77,78,79,80,81,82,83,87,88,89) have mixed types. Specify dtype option on import or set low_memory=False.
  df_epa = pd.read_csv("../../data/interim/EPA_joined.csv", sep=",")

In [33]:
df_epa

,CICLO,CCAA,PROV,NVIVI,NIVEL,NPERS,EDAD1,RELPP1,SEXO1,NCONY,...,SIDAC2,DAUSVAC,DAUSENF,DAUSOTR,TRAANT,AOI,RELLB4,FACTOREL,FACB2021,PESO
0,194,16,1,1,1,1,40,1,1,2,...,1,2.0,NaN,NaN,1,04,,193.90,174.32,174.32
1,194,16,1,1,1,2,30,2,6,1,...,1,NaN,NaN,NaN,1,03,,193.90,174.32,174.32
2,194,16,1,2,1,1,35,1,6,2,...,1,1.0,NaN,NaN,1,04,,252.32,225.37,225.37
3,194,16,1,2,1,2,30,2,1,1,...,1,1.0,NaN,NaN,1,04,,252.32,225.37,225.37
4,194,16,1,2,2,3,0,3,6,0,...,,NaN,NaN,NaN,,,,252.32,225.37,225.37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2516023,213,52,52,45198,1,2,65,2,1,1,...,NaN,NaN,NaN,NaN,NaN,9.0,NaN,65.17,NaN,NaN
2516024,213,52,52,45199,1,1,30,1,1,0,...,1.0,5.0,NaN,NaN,NaN,4.0,NaN,451.33,NaN,NaN
2516025,213,52,52,45200,1,1,65,1,1,0,...,NaN,NaN,NaN,NaN,NaN,9.0,NaN,154.66,NaN,NaN
2516026,213,52,52,45201,1,1,65,1,6,2,...,NaN,NaN,NaN,NaN,NaN,9.0,NaN,96.23,NaN,NaN
2516027,213,52,52,45201,1,2,65,2,1,1,...,NaN,NaN,NaN,NaN,NaN,9.0,NaN,96.23,NaN,NaN

In [34]:
df_epa.columns

Index(['CICLO', 'CCAA', 'PROV', 'NVIVI', 'NIVEL', 'NPERS', 'EDAD1', 'RELPP1',
       'SEXO1', 'NCONY', 'NPADRE', 'NMADRE', 'RELLMILI', 'ECIV1', 'PRONA1',
       'REGNA1', 'NAC1', 'EXREGNA1', 'ANORE1', 'NFORMA', 'RELLB1', 'EDADEST',
       'CURSR', 'NCURSR', 'CURSNR', 'OBJFORM', 'RELLB2', 'TRAREM', 'AYUDFA',
       'AUSENT', 'RZNOTB', 'VINCUL', 'NUEVEM', 'OCUP1', 'ACT1', 'SITU', 'SP',
       'DUCON1', 'DUCON2', 'DUCON3', 'TCONTM', 'TCONTD', 'DREN', 'DCOM',
       'PROEST', 'REGEST', 'PARCO1', 'PARCO2', 'HORASP', 'HORASH', 'HORASE',
       'EXTRA', 'EXTPAG', 'EXTNPG', 'RELLB3', 'TRAPLU', 'OCUPLU1', 'ACTPLU1',
       'SITPLU', 'HOREPLU', 'MASHOR', 'DISMAS', 'RZNDISH', 'HORDES', 'BUSOTR',
       'BUSCA', 'DESEA', 'FOBACT', 'NBUSCA', 'RZULT', 'ITBU', 'DISP', 'RZNDIS',
       'EMPANT', 'DTANT', 'OCUPA', 'ACTA', 'SITUA', 'OFEMP', 'SIDI1', 'SIDI2',
       'SIDI3', 'SIDAC1', 'SIDAC2', 'DAUSVAC', 'DAUSENF', 'DAUSOTR', 'TRAANT',
       'AOI', 'RELLB4', 'FACTOREL', 'FACB2021', 'PESO'],
      dtype='object')

In [35]:
bloque_demografico = ['CICLO', 'CCAA', 'PROV', 'NVIVI', 'NIVEL', 'NPERS', 'EDAD1', 'RELPP1','SEXO1', 'PESO']
bloque_educacion = ['NFORMA', 'EDADEST', 'CURSR', 'NCURSR', 'CURSNR']

# Dudoso de si se queda
bloque_migracion = ['PRONA1', 'REGNA1', 'NAC1', 'EXREGNA1', 'ANORE1']

In [36]:
columnas_bloques = [col for col in (bloque_demografico + bloque_educacion + bloque_migracion) if col in df_epa]

df_epa_filtrado = df_epa[columnas_bloques]

In [37]:
df_epa_filtrado.columns

Index(['CICLO', 'CCAA', 'PROV', 'NVIVI', 'NIVEL', 'NPERS', 'EDAD1', 'RELPP1',
       'SEXO1', 'PESO', 'NFORMA', 'EDADEST', 'CURSR', 'NCURSR', 'CURSNR',
       'PRONA1', 'REGNA1', 'NAC1', 'EXREGNA1', 'ANORE1'],
      dtype='object')

------------------------------------------------------------------------------------------------------------------------------------

Guardamos CSV del dataframe con solo las columnas que necesitamos. 

Cargar este CSV y no el anterior, ya que tarda mucho en leerse debido al tamaño del CSV.

In [38]:
# Guardamos en CSV el dataframe de 'df_epa_filtrado'

ruta = Path("../../data/interim")

# df_epa_filtrado.to_csv(ruta/"EPA_joined_clean_col.csv", index=False)

Cargamos de nuevo el CSV

In [39]:
df_epa_filtrado = pd.read_csv(ruta/"EPA_joined_clean_col.csv", sep=",")

/var/folders/18/2jngcg0x5csd3tyb3xj47rrm0000gn/T/ipykernel_55639/560084513.py:1: DtypeWarning: Columns (12,14,15,16,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df_epa_filtrado = pd.read_csv(ruta/"EPA_joined_clean_col.csv", sep=",")

In [40]:
df_epa_filtrado.head()

,CICLO,CCAA,PROV,NVIVI,NIVEL,NPERS,EDAD1,RELPP1,SEXO1,PESO,NFORMA,EDADEST,CURSR,NCURSR,CURSNR,PRONA1,REGNA1,NAC1,EXREGNA1,ANORE1
0,194,16,1,1,1,1,40,1,1,174.32,SU,19.0,3,,3,06,,1,,NaN
1,194,16,1,1,1,2,30,2,6,174.32,SU,20.0,3,,3,01,,1,,NaN
2,194,16,1,2,1,1,35,1,6,225.37,SU,22.0,3,,3,01,,1,,NaN
3,194,16,1,2,1,2,30,2,1,225.37,SU,22.0,3,,3,01,,1,,NaN
4,194,16,1,2,2,3,0,3,6,225.37,,NaN,,,,01,,1,,NaN

In [41]:
df_epa_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2516028 entries, 0 to 2516027
Data columns (total 20 columns):
 #   Column    Dtype
---  ------    -----
 0   CICLO     int64
 1   CCAA      int64
 2   PROV      int64
 3   NVIVI     int64
 4   NIVEL     int64
 5   NPERS     int64
 6   EDAD1     int64
 7   RELPP1    int64
 8   SEXO1     int64
 9   PESO      float64
 10  NFORMA    object
 11  EDADEST   float64
 12  CURSR     object
 13  NCURSR    object
 14  CURSNR    object
 15  PRONA1    object
 16  REGNA1    object
 17  NAC1      int64
 18  EXREGNA1  object
 19  ANORE1    float64
dtypes: float64(3), int64(10), object(7)
memory usage: 383.9+ MB

In [58]:
# Hace un informe detallado de cada una de las columnas.
profile = ProfileReport(df_epa_filtrado)
profile.to_notebook_iframe()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 19/19 [00:18<00:00,  1.01it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [42]:
df_epa_filtrado.isna().sum()

CICLO             0
CCAA              0
PROV              0
NVIVI             0
NIVEL             0
NPERS             0
EDAD1             0
RELPP1            0
SEXO1             0
PESO         946156
NFORMA       189413
EDADEST      389785
CURSR        189413
NCURSR      1208497
CURSNR       189413
PRONA1       149168
REGNA1      1171827
NAC1              0
EXREGNA1    1182721
ANORE1      2154498
dtype: int64

In [43]:
resumen_nulos = pd.DataFrame({
    'nulos': df_epa_filtrado.isna().sum(),
    'porcentaje': df_epa_filtrado.isna().mean() * 100
}).sort_values(by='nulos', ascending=False)

print(resumen_nulos)

            nulos  porcentaje
ANORE1    2154498   85.630923
NCURSR    1208497   48.031938
EXREGNA1  1182721   47.007466
REGNA1    1171827   46.574482
PESO       946156   37.605146
EDADEST    389785   15.492077
CURSNR     189413    7.528255
CURSR      189413    7.528255
NFORMA     189413    7.528255
PRONA1     149168    5.928710
SEXO1           0    0.000000
CCAA            0    0.000000
RELPP1          0    0.000000
EDAD1           0    0.000000
NPERS           0    0.000000
NIVEL           0    0.000000
NVIVI           0    0.000000
NAC1            0    0.000000
PROV            0    0.000000
CICLO           0    0.000000

### BLOQUE ORIGEN/MIGRACIÓN (Dudoso)
- ANORE1 - Años de residencia en España. --> +85% (¿eliminar?) --> 85% puede ser nacionales españoles que no han vivido más de un año fuera de España, contrastar con NAC1(mirar % por cada tipo- 3).
- EXREGNA1 - Región de nacionalidad extranjera. --> +47% (¿eliminar?) --> 47% puede ser personas solo nacionales.
- REGNA1 - Región de nacimiento (extranjero). --> +46% (¿eliminar?) --> 46% puede ser personas solo nacionales.
- PRONA1 - Provincia de nacimiento (España). --> +5%


### BLOQUE EDUCACIÓN (Sí) (todas las columnas de este bloque)
- NCURSR - Nivel de esa formación. --> +48% (¿eliminar?) --> ¿Sin estudios en curso?
- EDADEST - Edad a la que alcanzó el nivel máximo de estudios. --> +15% --> personas sin estudios¿?
- CURSNR - Formación no reglada reciente. --> +7%
- CURSR - Formación reglada reciente. --> +7%
- NFORMA - Nivel educativo. --> +7% --> ver si estas 3 variables coinciden los 3 como nulos.

---------------------------------------------------------------------------------

In [44]:
# Nos vamos a quedar solo con aquellos individuos que tengan más de 16 años, para ello, nos tenemos que quedar con NIVEL = 1.

df_epa_filtrado

,CICLO,CCAA,PROV,NVIVI,NIVEL,NPERS,EDAD1,RELPP1,SEXO1,PESO,NFORMA,EDADEST,CURSR,NCURSR,CURSNR,PRONA1,REGNA1,NAC1,EXREGNA1,ANORE1
0,194,16,1,1,1,1,40,1,1,174.32,SU,19.0,3,,3,06,,1,,NaN
1,194,16,1,1,1,2,30,2,6,174.32,SU,20.0,3,,3,01,,1,,NaN
2,194,16,1,2,1,1,35,1,6,225.37,SU,22.0,3,,3,01,,1,,NaN
3,194,16,1,2,1,2,30,2,1,225.37,SU,22.0,3,,3,01,,1,,NaN
4,194,16,1,2,2,3,0,3,6,225.37,,NaN,,,,01,,1,,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2516023,213,52,52,45198,1,2,65,2,1,NaN,SU,29.0,3.0,NaN,3.0,52.0,NaN,1,NaN,NaN
2516024,213,52,52,45199,1,1,30,1,1,NaN,SU,23.0,3.0,NaN,3.0,18.0,NaN,1,NaN,NaN
2516025,213,52,52,45200,1,1,65,1,1,NaN,S1,52.0,3.0,NaN,3.0,52.0,NaN,1,NaN,NaN
2516026,213,52,52,45201,1,1,65,1,6,NaN,P2,14.0,3.0,NaN,3.0,52.0,NaN,1,NaN,NaN
2516027,213,52,52,45201,1,2,65,2,1,NaN,P2,14.0,3.0,NaN,3.0,52.0,NaN,1,NaN,NaN

In [45]:
df_epa_filtrado_16 = df_epa_filtrado[df_epa_filtrado['NIVEL'] == 1]
df_epa_filtrado_16

,CICLO,CCAA,PROV,NVIVI,NIVEL,NPERS,EDAD1,RELPP1,SEXO1,PESO,NFORMA,EDADEST,CURSR,NCURSR,CURSNR,PRONA1,REGNA1,NAC1,EXREGNA1,ANORE1
0,194,16,1,1,1,1,40,1,1,174.32,SU,19.0,3,,3,06,,1,,NaN
1,194,16,1,1,1,2,30,2,6,174.32,SU,20.0,3,,3,01,,1,,NaN
2,194,16,1,2,1,1,35,1,6,225.37,SU,22.0,3,,3,01,,1,,NaN
3,194,16,1,2,1,2,30,2,1,225.37,SU,22.0,3,,3,01,,1,,NaN
5,194,16,1,3,1,1,65,1,1,241.00,SU,19.0,3,,3,20,,1,,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2516023,213,52,52,45198,1,2,65,2,1,NaN,SU,29.0,3.0,NaN,3.0,52.0,NaN,1,NaN,NaN
2516024,213,52,52,45199,1,1,30,1,1,NaN,SU,23.0,3.0,NaN,3.0,18.0,NaN,1,NaN,NaN
2516025,213,52,52,45200,1,1,65,1,1,NaN,S1,52.0,3.0,NaN,3.0,52.0,NaN,1,NaN,NaN
2516026,213,52,52,45201,1,1,65,1,6,NaN,P2,14.0,3.0,NaN,3.0,52.0,NaN,1,NaN,NaN
2516027,213,52,52,45201,1,2,65,2,1,NaN,P2,14.0,3.0,NaN,3.0,52.0,NaN,1,NaN,NaN

In [46]:
# Eliminamos la variable 'NIVEL'
df_epa_filtrado_16 = df_epa_filtrado_16.drop('NIVEL', axis=1)

In [47]:
df_epa_filtrado_16

,CICLO,CCAA,PROV,NVIVI,NPERS,EDAD1,RELPP1,SEXO1,PESO,NFORMA,EDADEST,CURSR,NCURSR,CURSNR,PRONA1,REGNA1,NAC1,EXREGNA1,ANORE1
0,194,16,1,1,1,40,1,1,174.32,SU,19.0,3,,3,06,,1,,NaN
1,194,16,1,1,2,30,2,6,174.32,SU,20.0,3,,3,01,,1,,NaN
2,194,16,1,2,1,35,1,6,225.37,SU,22.0,3,,3,01,,1,,NaN
3,194,16,1,2,2,30,2,1,225.37,SU,22.0,3,,3,01,,1,,NaN
5,194,16,1,3,1,65,1,1,241.00,SU,19.0,3,,3,20,,1,,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2516023,213,52,52,45198,2,65,2,1,NaN,SU,29.0,3.0,NaN,3.0,52.0,NaN,1,NaN,NaN
2516024,213,52,52,45199,1,30,1,1,NaN,SU,23.0,3.0,NaN,3.0,18.0,NaN,1,NaN,NaN
2516025,213,52,52,45200,1,65,1,1,NaN,S1,52.0,3.0,NaN,3.0,52.0,NaN,1,NaN,NaN
2516026,213,52,52,45201,1,65,1,6,NaN,P2,14.0,3.0,NaN,3.0,52.0,NaN,1,NaN,NaN
2516027,213,52,52,45201,2,65,2,1,NaN,P2,14.0,3.0,NaN,3.0,52.0,NaN,1,NaN,NaN

In [48]:
df_epa_filtrado_16.to_csv(ruta/"EPA_joined_clean_col_2.csv", index=False)

-----------------------------------------------------------------------------------------

In [49]:
# Cargamos el CSV

ruta = Path("../../data/interim")
df_epa = pd.read_csv(ruta/"EPA_joined_clean_col_2.csv", sep=",")

/var/folders/18/2jngcg0x5csd3tyb3xj47rrm0000gn/T/ipykernel_55639/3216389319.py:4: DtypeWarning: Columns (14,15,17) have mixed types. Specify dtype option on import or set low_memory=False.
  df_epa = pd.read_csv(ruta/"EPA_joined_clean_col_2.csv", sep=",")

In [50]:
df_epa

,CICLO,CCAA,PROV,NVIVI,NPERS,EDAD1,RELPP1,SEXO1,PESO,NFORMA,EDADEST,CURSR,NCURSR,CURSNR,PRONA1,REGNA1,NAC1,EXREGNA1,ANORE1
0,194,16,1,1,1,40,1,1,174.32,SU,19.0,3.0,,3.0,06,,1,,NaN
1,194,16,1,1,2,30,2,6,174.32,SU,20.0,3.0,,3.0,01,,1,,NaN
2,194,16,1,2,1,35,1,6,225.37,SU,22.0,3.0,,3.0,01,,1,,NaN
3,194,16,1,2,2,30,2,1,225.37,SU,22.0,3.0,,3.0,01,,1,,NaN
4,194,16,1,3,1,65,1,1,241.00,SU,19.0,3.0,,3.0,20,,1,,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2151109,213,52,52,45198,2,65,2,1,NaN,SU,29.0,3.0,NaN,3.0,52.0,NaN,1,NaN,NaN
2151110,213,52,52,45199,1,30,1,1,NaN,SU,23.0,3.0,NaN,3.0,18.0,NaN,1,NaN,NaN
2151111,213,52,52,45200,1,65,1,1,NaN,S1,52.0,3.0,NaN,3.0,52.0,NaN,1,NaN,NaN
2151112,213,52,52,45201,1,65,1,6,NaN,P2,14.0,3.0,NaN,3.0,52.0,NaN,1,NaN,NaN
2151113,213,52,52,45201,2,65,2,1,NaN,P2,14.0,3.0,NaN,3.0,52.0,NaN,1,NaN,NaN

## BLOQUE DEMOGRÁFICO
- ✅ CICLO - Período de referencia (año/trimestre).
- ✅ CCAA - Comunidad autónoma.
- ✅ PROV - Provincia.
- ⬜ NVIVI - Identificador de vivienda. (no hay que hacer descodificación)
- ⬜ NPERS - Identificador de persona dentro del hogar. (no hay que hacer descodificación)
- ✅ EDAD1 - Edad.
- ✅ SEXO1 - Sexo.
- ✅ RELPP1 - Relación con la persona de referencia.

## FUNCIÓN PARA DESCODIFICAR

In [51]:
def decodif(df_original: pd.DataFrame, df_descod: list[pd.DataFrame]) -> pd.DataFrame:
    """
    Descodifica una o varias columnas de un DataFrame usando tablas descodificadoras de referencia.

    Parameters: 
        df_original (pd.DataFrame): DataFrame original. 
        df:descod (list[pd.DataFrame]): Lista de configuraciones de descodificación.
 
    Returns: 
        pd.DataFrame: DataFrame original con la/s columna/s descodificada/s.
    
    """
    
    df_copy = df_original.copy()
    col_order = df_copy.columns
    
    len_df_descod = len(df_descod)



    if len_df_descod == 1:
        if df_descod[0].columns[0] in col_order:
            df_copy = df_copy.merge(df_descod[0], on = df_descod[0].columns[0], how = 'left').drop(df_descod[0].columns[0], axis = 1)
            df_copy = df_copy.rename(columns={df_descod[0].columns[1]:df_descod[0].columns[0]})[col_order]
        else:
            print(f'No se encuentra {df_descod[0].columns[0]} entre las variables del DataFrame. No se puede descodificar.')
    elif len_df_descod > 1: 
        for descod in df_descod:
            if  descod.columns[0] in col_order:
                df_copy = df_copy.merge(descod, on = descod.columns[0], how = 'left').drop(descod.columns[0], axis = 1)
                df_copy = df_copy.rename(columns = {descod.columns[1]:descod.columns[0]})[col_order]
            else: 
                print(f'No se encuentra {descod.columns[0]} entre las variables del DataFrame. No se puede descodificar.')
    else: 
        print("ERROR: no hay dataframe de descodificación o") 
    
    return df_copy

In [52]:
## DataFrames de descodificación

## CICLO - Periódo de referencia (año/trimestre)
descod_ciclo = pd.DataFrame({
    'CICLO': [194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213], 
    'descripcion': ['2021T1', '2021T2', '2021T3', '2021T4', '2022T1', '2022T2', '2022T3', '2022T4', '2023T1', '2023T2',
                    '2023T3', '2023T4', '2024T1', '2024T2', '2024T3', '2024T4', '2025T1', '2025T2', '2025T3', '2025T4']
})

## CCAA - Comunidad Autónoma
descod_ccaa = pd.DataFrame({
    'CCAA': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 51, 52], 
    'descripcion': ['Andalucía', 'Aragón', 'Asturias, Principado de', 'Balears, Illes',
                   'Canarias', 'Cantabria', 'Castilla y León', 'Castilla-La Mancha', 
                   'Cataluña', 'Comunitat Valenciana', 'Extremadura', 'Galicia', 
                   'Madrid, Comunidad de', 'Murcia, Región de', 'Navarra, Comunidad Foral de', 
                   'País Vasco', 'Rioja, La', 'Ceuta', 'Melilla']
})


## PROV - Provincia
descod_prov = pd.DataFrame({
    'PROV': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 ,12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 
             31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52], 
    'descripcion': ['Araba/Álava', 'Albacete', 'Alicante/Alacant', 'Almería', 'Ávila', 'Badajoz', 'Balears, Illes', 'Barcelona',
                    'Burgos', 'Cáceres', 'Cádiz', 'Castellón /Castelló', 'Ciudad Real', 'Córdoba', 'Coruña, A', 'Cuenca', 'Girona',
                    'Granada', 'Guadalajara', 'Gipuzkoa', 'Huelva', 'Huesca', 'Jaén', 'León', 'Lleida', 'Rioja, La', 'Lugo', 'Madrid', 
                    'Málaga', 'Murcia', 'Navarra', 'Ourense', 'Asturias', 'Palencia', 'Palmas, Las', 'Pontevedra', 'Salamanca', 
                    'Santa Cruz de Tenerife', 'Cantabria', 'Segovia', 'Sevilla', 'Soria', 'Tarragona', 'Teruel', 'Toledo', 'Valencia/València', 
                    'Valladolid', 'Bizkaia', 'Zamora', 'Zaragoza', 'Ceuta', 'Melilla']
})


## EDAD1 - Edad (¿Seguro que queremos descodificar?)
descod_edad1 = pd.DataFrame({
    'EDAD1': [0, 5, 10, 16, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65], 
    'descripcion': ['0-4', '5-9', '10-15', '16-19', '20-24', '25-29', 
                    '30-34', '35-39', '40-44', '45-49', '50-54', '55-59', 
                    '60-64', '+65']
})

## SEXO1 - Sexo
descod_sexo1 = pd.DataFrame({
    'SEXO1': [1, 6], 
    'descripcion': ['Hombre', 'Mujer']
})

## RELPP1 - Relación con la persona de referencia
descod_relpp1 = pd.DataFrame({
    'RELPP1': [1, 2, 3, 4, 5, 6, 7, 8, 9], 
    'descripcion': ['Persona de referencia (p.r.)', 
                    'Cónyuge o pareja de la p.r.', 
                    'Hijo/a, hijastro/a (de la p.r o pareja del mismo)', 
                    'Yerno , nuera de la p.r. o de su pareja (o pareja del hijo/a, hijastro/a)', 
                    'Nieto/a, nieto/a de la p.r. o de su pareja (incluye nietastros/as e ambos)', 
                    'Padre, madre, suegro/a de la p.r o pareja de los mismos (padrastro, madrastra)', 
                    'Otro pariente de la p.r (o pareja del mismo)', 'Persona del servicio doméstico', 
                    'Sin parentesco con la p.r.']
})

## Lista de descodificadores: 
list_descod = [descod_ciclo, 
               descod_ccaa, 
               descod_prov, 
               descod_edad1, 
               descod_sexo1, 
               descod_relpp1]

In [53]:
df_epa_decod = decodif(df_epa, list_descod)

In [54]:
df_epa_decod

,CICLO,CCAA,PROV,NVIVI,NPERS,EDAD1,RELPP1,SEXO1,PESO,NFORMA,EDADEST,CURSR,NCURSR,CURSNR,PRONA1,REGNA1,NAC1,EXREGNA1,ANORE1
0,2021T1,País Vasco,Araba/Álava,1,1,40-44,Persona de referencia (p.r.),Hombre,174.32,SU,19.0,3.0,,3.0,06,,1,,NaN
1,2021T1,País Vasco,Araba/Álava,1,2,30-34,Cónyuge o pareja de la p.r.,Mujer,174.32,SU,20.0,3.0,,3.0,01,,1,,NaN
2,2021T1,País Vasco,Araba/Álava,2,1,35-39,Persona de referencia (p.r.),Mujer,225.37,SU,22.0,3.0,,3.0,01,,1,,NaN
3,2021T1,País Vasco,Araba/Álava,2,2,30-34,Cónyuge o pareja de la p.r.,Hombre,225.37,SU,22.0,3.0,,3.0,01,,1,,NaN
4,2021T1,País Vasco,Araba/Álava,3,1,+65,Persona de referencia (p.r.),Hombre,241.00,SU,19.0,3.0,,3.0,20,,1,,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2151109,2025T4,Melilla,Melilla,45198,2,+65,Cónyuge o pareja de la p.r.,Hombre,NaN,SU,29.0,3.0,NaN,3.0,52.0,NaN,1,NaN,NaN
2151110,2025T4,Melilla,Melilla,45199,1,30-34,Persona de referencia (p.r.),Hombre,NaN,SU,23.0,3.0,NaN,3.0,18.0,NaN,1,NaN,NaN
2151111,2025T4,Melilla,Melilla,45200,1,+65,Persona de referencia (p.r.),Hombre,NaN,S1,52.0,3.0,NaN,3.0,52.0,NaN,1,NaN,NaN
2151112,2025T4,Melilla,Melilla,45201,1,+65,Persona de referencia (p.r.),Mujer,NaN,P2,14.0,3.0,NaN,3.0,52.0,NaN,1,NaN,NaN
2151113,2025T4,Melilla,Melilla,45201,2,+65,Cónyuge o pareja de la p.r.,Hombre,NaN,P2,14.0,3.0,NaN,3.0,52.0,NaN,1,NaN,NaN

In [55]:
df_epa_decod.sample(10)

,CICLO,CCAA,PROV,NVIVI,NPERS,EDAD1,RELPP1,SEXO1,PESO,NFORMA,EDADEST,CURSR,NCURSR,CURSNR,PRONA1,REGNA1,NAC1,EXREGNA1,ANORE1
1078820,2023T2,Andalucía,Málaga,28817,1,+65,Persona de referencia (p.r.),Mujer,505.68,S1,15.0,3.0,NaN,1.0,29.0,NaN,1,NaN,47.0
78885,2021T1,"Asturias, Principado de",Asturias,37537,2,40-44,Cónyuge o pareja de la p.r.,Hombre,208.83,SU,25.0,3.0,,3.0,33,,1,,NaN
578034,2022T2,País Vasco,Araba/Álava,84,1,55-59,Persona de referencia (p.r.),Hombre,237.38,SP,18.0,3.0,,1.0,47,,1,,NaN
1703769,2024T4,"Madrid, Comunidad de",Madrid,25041,2,60-64,Cónyuge o pareja de la p.r.,Mujer,NaN,SP,17.0,3.0,NaN,3.0,28.0,NaN,1,NaN,NaN
1804026,2025T1,"Madrid, Comunidad de",Madrid,23962,2,+65,Cónyuge o pareja de la p.r.,Hombre,NaN,SG,17.0,3.0,NaN,3.0,28.0,NaN,1,NaN,NaN
324823,2021T3,Canarias,Santa Cruz de Tenerife,40623,1,+65,Persona de referencia (p.r.),Mujer,723.62,SG,18.0,3.0,,3.0,,100,3,100,3.0
1109965,2023T2,Andalucía,Sevilla,43927,3,20-24,"Hijo/a, hijastro/a (de la p.r o pareja del mismo)",Hombre,620.19,SG,19.0,1.0,SU,3.0,NaN,310.0,2,310.0,6.0
1677615,2024T4,Andalucía,Córdoba,12307,2,60-64,Cónyuge o pareja de la p.r.,Hombre,NaN,SU,24.0,3.0,NaN,1.0,13.0,NaN,1,NaN,NaN
573194,2022T1,Castilla y León,Zamora,51636,1,+65,Persona de referencia (p.r.),Mujer,87.88,P2,14.0,3.0,,3.0,49,,1,,NaN
1578283,2024T3,Galicia,"Coruña, A",13958,2,45-49,Cónyuge o pareja de la p.r.,Hombre,NaN,SP,17.0,3.0,NaN,3.0,15.0,NaN,1,NaN,NaN

## BLOQUE ORIGEN/MIGRACIÓN
- ✅ PRONA1 - Provincia de nacimiento (España).
- ✅ REGNA1 - Región de nacimiento (extranjero).
- ✅ NAC1 - Nacionalidad.
- ✅ EXREGNA1 - Región de nacionalidad extranjera.
- ⬜ ANORE1 - Años de residencia en España. -> Diría que no hace falta modificarla.

In [56]:
# REGNA - Región de nacionalidad

descod_regna1 = pd.DataFrame({
    'REGNA1': ['115', '125', '128', '100', '200', '300', '310', '350', '400', '410', '420', '500'],
    'descripcion': [
        'UE-15',
        'UE-25 (no UE-15)',
        'UE-28 (no UE-27)',
        'Resto de Europa',
        'África',
        'América del Norte',
        'Centroamérica y Caribe',
        'Sudamérica',
        'Asia Oriental (Lejano Oriente)',
        'Asia Occidental (Oriente Próximo)',
        'Asia del Sur y Sudoeste',
        'Oceanía'
    ]
})

In [57]:
# EXREGNA1 - Región de nacionalidad, incluyendo apátridas

descod_exregna1 = pd.DataFrame({
    'EXREGNA1': ['115', '125', '128', '100', '200', '300', '310', '350', '400', '410', '420', '500', '999'],
    'descripcion': [
        'UE-15',
        'UE-25 (no UE-15)',
        'UE-28 (no UE-27)',
        'Resto de Europa',
        'África',
        'América del Norte',
        'Centroamérica y Caribe',
        'Sudamérica',
        'Asia Oriental (Lejano Oriente)',
        'Asia Occidental (Oriente Próximo)',
        'Asia del Sur y Sudoeste',
        'Oceanía',
        'Apátridas'
    ]
})

In [58]:
# N_ANORE - Años de residencia en España

In [59]:
# NAC1 - Nacionalidad

descod_nac1 = pd.DataFrame({
    'NAC1': [1, 2, 3],
    'descripcion': [
        'Española',
        'Española y doble nacionalidad',
        'Extranjera'
    ]
})

In [60]:
# PRONA1 - Provincia

descod_prona1 = pd.DataFrame({
    'PRONA1': [f'{i:02d}' for i in range(1, 53)],
    'descripcion': [
        'Araba/Álava', 'Albacete', 'Alicante/Alacant', 'Almería', 'Ávila',
        'Badajoz', 'Balears, Illes', 'Barcelona', 'Burgos', 'Cáceres',
        'Cádiz', 'Castellón /Castelló', 'Ciudad Real', 'Córdoba', 'Coruña, A',
        'Cuenca', 'Girona', 'Granada', 'Guadalajara', 'Gipuzkoa',
        'Huelva', 'Huesca', 'Jaén', 'León', 'Lleida',
        'Rioja, La', 'Lugo', 'Madrid', 'Málaga', 'Murcia',
        'Navarra', 'Ourense', 'Asturias', 'Palencia', 'Palmas, Las',
        'Pontevedra', 'Salamanca', 'Santa Cruz de Tenerife', 'Cantabria', 'Segovia',
        'Sevilla', 'Soria', 'Tarragona', 'Teruel', 'Toledo',
        'Valencia/València', 'Valladolid', 'Bizkaia', 'Zamora', 'Zaragoza',
        'Ceuta', 'Melilla'
    ]
})

In [61]:
list_descod_ampliada = [
    descod_ciclo,
    descod_ccaa,
    descod_prov,
    descod_edad1,
    descod_sexo1,
    descod_relpp1,
    descod_regna1,
    descod_exregna1,
    descod_nac1,
    descod_prona1
]

In [62]:
df_epa_decod = decodif(df_epa, list_descod_ampliada)

In [63]:
df_epa_decod.sample(10).T

,1915775,18426,923423,38854,385759,1923333,1178588,672509,1704890,722613
CICLO,2025T2,2021T1,2023T1,2021T1,2021T4,2025T2,2023T3,2022T2,2024T4,2022T3
CCAA,Andalucía,Cataluña,Cataluña,Cataluña,Galicia,"Navarra, Comunidad Foral de","Madrid, Comunidad de",Cataluña,"Madrid, Comunidad de",Castilla-La Mancha
PROV,Málaga,Barcelona,Barcelona,Girona,"Coruña, A",Navarra,Madrid,Tarragona,Madrid,Cuenca
NVIVI,27376,8730,7577,18349,16106,30987,24275,45643,25558,16138
NPERS,2,2,1,1,2,4,1,1,3,2
EDAD1,35-39,55-59,+65,60-64,55-59,20-24,+65,+65,+65,45-49
RELPP1,Cónyuge o pareja de la p.r.,Cónyuge o pareja de la p.r.,Persona de referencia (p.r.),Persona de referencia (p.r.),Cónyuge o pareja de la p.r.,"Hijo/a, hijastro/a (de la p.r o pareja del mismo)",Persona de referencia (p.r.),Persona de referencia (p.r.),"Padre, madre, suegro/a de la p.r o pareja de l...",Cónyuge o pareja de la p.r.
SEXO1,Hombre,Hombre,Mujer,Hombre,Hombre,Hombre,Mujer,Mujer,Mujer,Hombre
PESO,NaN,1100.94,864.06,399.84,130.02,NaN,542.99,331.14,NaN,476.57
NFORMA,SP,S1,P2,SP,SU,SG,S1,S1,SU,S1
EDADEST,22.0,13.0,12.0,18.0,20.0,18.0,15.0,14.0,23.0,17.0
CURSR,3.0,3.0,3.0,3.0,3.0,1.0,3.0,3.0,3.0,3.0
NCURSR,NaN,,,,,SU,NaN,,NaN,
CURSNR,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
PRONA1,NaN,Jaén,Lugo,Barcelona,"Coruña, A",NaN,NaN,Tarragona,NaN,NaN
REGNA1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Asia Oriental (Lejano Oriente)
NAC1,Española,Española,Española,Española,Española,Española,Española,Española,Extranjera,Extranjera
EXREGNA1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Asia Oriental (Lejano Oriente)
ANORE1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,24.0

In [64]:
print(df_epa_decod["NAC1"].unique())
print(df_epa_decod["EXREGNA1"].unique())
print(df_epa_decod["REGNA1"].unique())
print(df_epa_decod["PRONA1"].unique())

['Española' 'Extranjera' 'Española y doble nacionalidad']
[nan 'África' 'Resto de Europa' 'Sudamérica' 'UE-15' 'UE-28 (no UE-27)'
 'Asia del Sur y Sudoeste' 'Centroamérica y Caribe' 'América del Norte'
 'Asia Oriental (Lejano Oriente)' 'Apátridas' 'UE-25 (no UE-15)' 'Oceanía'
 'Asia Occidental (Oriente Próximo)']
[nan 'África' 'Resto de Europa' 'Sudamérica' 'UE-15' 'UE-28 (no UE-27)'
 'Asia del Sur y Sudoeste' 'Asia Occidental (Oriente Próximo)'
 'Centroamérica y Caribe' 'América del Norte'
 'Asia Oriental (Lejano Oriente)' 'UE-25 (no UE-15)' 'Oceanía']
['Badajoz' 'Araba/Álava' 'Gipuzkoa' 'Burgos' nan 'Salamanca' 'Navarra'
 'Bizkaia' 'Zamora' 'Cáceres' 'Cantabria' 'Valladolid' 'Zaragoza'
 'Rioja, La' 'Sevilla' 'León' 'Segovia' 'Ávila' 'Madrid' 'Ourense'
 'Toledo' 'Ciudad Real' 'Murcia' 'Asturias' 'Málaga' 'Soria' 'Almería'
 'Granada' 'Teruel' 'Girona' 'Castellón /Castelló' 'Córdoba' 'Cádiz'
 'Barcelona' 'Palencia' 'Pontevedra' 'Jaén' 'Tarragona' 'Alicante/Alacant'
 'Lugo' 'Cuenca' 'Coruña, A' 'Albacete' 'Valencia/València' 'Ceuta'
 'Santa Cruz de Tenerife' 'Balears, Illes' 'Melilla' 'Huesca'
 'Guadalajara' 'Huelva' 'Lleida' 'Palmas, Las']

## BLOQUE EDUCACIÓN

- ✅ NFORMA - Nivel educativo.
- ⬜ EDADEST - Edad a la que alcanzó el nivel máximo de estudios. -> Diría que no hace falta pasarlo
- ✅ CURSR - Formación reglada reciente.
- ✅ NCURSR - Nivel de esa formación.
- ⬜ CURSNR - Formación no reglada reciente. -> No encuentro la decodificación

In [65]:
# NFORMA - Nivel educativo

descod_nforma = pd.DataFrame({
    'NFORMA': ['AN', 'P1', 'P2', 'S1', 'SG', 'SP', 'SU'],
    'descripcion': [
        'Analfabetos (código 01 en CNED-2014), (código 80 en CNED-2000)',
        'Educación primaria incompleta (código 02 en CNED-2014), (código 11 en CNED-2000)',
        'Educación primaria (código 10 en CNED-2014), (código 12 en CNED 2000)',
        'Primera etapa de educación secundaria (códigos 21-24 en CNED-2014), (códigos 21-23, 31, 36* en CNED-2000)',
        'Segunda etapa de educación secundaria. Orientación general (código 32 en CNED-2014), (código 32 en CNED-2000)',
        'Segunda etapa de educación secundaria. Orientación profesional (incluye educación postsecundaria no superior) (códigos 33-35, 38**, 41 en CNED-2014), (códigos 33, 34, 41 en CNED-2000)',
        'Educación superior (códigos 51, 52, 61-63, 71-75, 81 en CNED-2014), (códigos 50-56, 59, 61 en CNED-2000)'
    ]
})

In [66]:
# CURSR - Formación reglada reciente

descod_cursr = pd.DataFrame({
    'CURSR': [1, 2, 3],
    'descripcion': [
        'Sí',
        'Estudiante en vacaciones',
        'No'
    ]
})

In [67]:
# NCURSR - Nivel de esa formación

descod_ncursr = pd.DataFrame({
    'NCURSR': ['PR', 'S1', 'SG', 'SP', 'SU'],
    'descripcion': [
        'Educación primaria (códigos 11-13 en CNED-2014), (códigos 11-13 en CNED-2000)',
        'Primera etapa de educación secundaria (códigos 21-23 en CNED-2014), (códigos 22, 23, 36** en CNED-2000)',
        'Segunda etapa de educación secundaria. Orientación general (códigos 31, 32 en CNED-2014), (código 32 en CNED-2000)',
        'Segunda etapa de educación secundaria. Orientación profesional (incluye educación postsecundaria no superior) (códigos 33-35*, 36-37, 38***, 41 en CNED-2014), (códigos 33, 34 en CNED-2000)',
        'Educación superior (códigos 51, 52, 61-63, 71-75, 81 en CNED-2014), (códigos 50-52, 54-56, 59, 61 en CNED-2000)'
    ]
})

In [68]:
list_descod_ampliada2 = [
    descod_ciclo,
    descod_ccaa,
    descod_prov,
    descod_edad1,
    descod_sexo1,
    descod_relpp1,
    descod_regna1,
    descod_exregna1,
    descod_nac1,
    descod_prona1,
    descod_nforma,
    descod_cursr,
    descod_ncursr
]

In [70]:
df_epa_decod = decodif(df_epa, list_descod_ampliada2)

In [71]:
df_epa_decod.sample(10).T

,613343,1319722,1044789,963811,872904,773310,1616690,504545,294126,321768
CICLO,2022T2,2023T4,2023T2,2023T1,2022T4,2022T3,2024T3,2022T1,2021T3,2021T3
CCAA,Cataluña,Andalucía,Comunitat Valenciana,"Madrid, Comunidad de",Canarias,Cantabria,"Asturias, Principado de",Castilla-La Mancha,"Madrid, Comunidad de",Galicia
PROV,Girona,Sevilla,Castellón /Castelló,Madrid,"Palmas, Las",Cantabria,Asturias,Guadalajara,Madrid,Pontevedra
NVIVI,17112,41631,12289,27180,35942,40600,32609,18798,25976,39130
NPERS,4,3,1,1,1,1,1,2,1,3
EDAD1,20-24,16-19,+65,+65,55-59,50-54,45-49,+65,30-34,16-19
RELPP1,Otro pariente de la p.r (o pareja del mismo),"Hijo/a, hijastro/a (de la p.r o pareja del mismo)",Persona de referencia (p.r.),Persona de referencia (p.r.),Persona de referencia (p.r.),Persona de referencia (p.r.),Persona de referencia (p.r.),Cónyuge o pareja de la p.r.,Persona de referencia (p.r.),"Hijo/a, hijastro/a (de la p.r o pareja del mismo)"
SEXO1,Mujer,Hombre,Hombre,Mujer,Mujer,Mujer,Hombre,Hombre,Hombre,Mujer
PESO,424.98,321.69,306.14,728.41,211.53,126.61,NaN,123.55,1188.44,179.77
NFORMA,Segunda etapa de educación secundaria. Orienta...,Segunda etapa de educación secundaria. Orienta...,Primera etapa de educación secundaria (códigos...,Educación primaria incompleta (código 02 en CN...,"Educación superior (códigos 51, 52, 61-63, 71-...","Educación superior (códigos 51, 52, 61-63, 71-...",Segunda etapa de educación secundaria. Orienta...,Educación primaria incompleta (código 02 en CN...,"Educación superior (códigos 51, 52, 61-63, 71-...",Primera etapa de educación secundaria (códigos...
EDADEST,18.0,18.0,14.0,14.0,18.0,23.0,20.0,10.0,26.0,15.0
CURSR,Sí,Sí,No,No,No,No,No,No,Sí,Sí
NCURSR,"Educación superior (códigos 51, 52, 61-63, 71-...","Educación superior (códigos 51, 52, 61-63, 71-...",NaN,NaN,NaN,NaN,NaN,NaN,"Educación superior (códigos 51, 52, 61-63, 71-...",Segunda etapa de educación secundaria. Orienta...
CURSNR,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
PRONA1,Girona,NaN,NaN,Badajoz,NaN,Cantabria,NaN,Cuenca,NaN,Pontevedra
REGNA1,NaN,NaN,NaN,NaN,Centroamérica y Caribe,NaN,NaN,NaN,UE-28 (no UE-27),NaN
NAC1,Española y doble nacionalidad,Española,Española,Española,Española,Española,Española,Española,Extranjera,Española
EXREGNA1,África,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UE-28 (no UE-27),NaN
ANORE1,NaN,NaN,NaN,NaN,18.0,NaN,NaN,NaN,6.0,NaN

In [72]:
print(df_epa_decod["NFORMA"].unique())
print(df_epa_decod["CURSR"].unique())
print(df_epa_decod["NCURSR"].unique())

['Educación superior (códigos 51, 52, 61-63, 71-75, 81 en CNED-2014), (códigos 50-56, 59, 61 en CNED-2000)'
 'Segunda etapa de educación secundaria. Orientación general (código 32 en CNED-2014), (código 32 en CNED-2000)'
 'Primera etapa de educación secundaria (códigos 21-24 en CNED-2014), (códigos 21-23, 31, 36* en CNED-2000)'
 'Segunda etapa de educación secundaria. Orientación profesional (incluye educación postsecundaria no superior) (códigos 33-35, 38**, 41 en CNED-2014), (códigos 33, 34, 41 en CNED-2000)'
 'Educación primaria (código 10 en CNED-2014), (código 12 en CNED 2000)'
 'Educación primaria incompleta (código 02 en CNED-2014), (código 11 en CNED-2000)'
 'Analfabetos (código 01 en CNED-2014), (código 80 en CNED-2000)']
['No' 'Sí' 'Estudiante en vacaciones']
[nan
 'Segunda etapa de educación secundaria. Orientación profesional (incluye educación postsecundaria no superior) (códigos 33-35*, 36-37, 38***, 41 en CNED-2014), (códigos 33, 34 en CNED-2000)'
 'Segunda etapa de educación secundaria. Orientación general (códigos 31, 32 en CNED-2014), (código 32 en CNED-2000)'
 'Primera etapa de educación secundaria (códigos 21-23 en CNED-2014), (códigos 22, 23, 36** en CNED-2000)'
 'Educación superior (códigos 51, 52, 61-63, 71-75, 81 en CNED-2014), (códigos 50-52, 54-56, 59, 61 en CNED-2000)'
 'Educación primaria (códigos 11-13 en CNED-2014), (códigos 11-13 en CNED-2000)']

---------------------------------------------------------------------------------

### Cambio de nombre en las columnas.

#### BLOQUE DEMOGRÁFICO
- CICLO - Período de referencia (año/trimestre).
- CCAA - Comunidad autónoma.
- PROV - Provincia.
- NVIVI - Identificador de vivienda. (no hay que hacer descodificación)
- NPERS - Identificador de persona dentro del hogar. (no hay que hacer descodificación)
- EDAD1 - Edad.
- SEXO1 - Sexo.
- RELPP1 - Relación con la persona de referencia.

#### BLOQUE ORIGEN/MIGRACIÓN
- PRONA1 - Provincia de nacimiento (España).
- REGNA1 - Región de nacimiento (extranjero).
- NAC1 - Nacionalidad.
- EXREGNA1 - Región de nacionalidad extranjera.
- ANORE1 - Años de residencia en España. -> Diría que no hace falta modificarla.

#### BLOQUE EDUCACIÓN

- NFORMA - Nivel educativo.
- EDADEST - Edad a la que alcanzó el nivel máximo de estudios. -> Diría que no hace falta pasarlo
- CURSR - Formación reglada reciente.
- NCURSR - Nivel de esa formación.
- CURSNR - Formación no reglada reciente. -> No encuentro la decodificación

In [73]:
def cambio_nombre_col(df: pd.DataFrame, dict_cols: dict) -> pd.DataFrame:
    
    df_copy = df.copy()
    col = df_copy.columns

    cols_no_encontradas = [x for x in dict_cols.keys() if x not in col]
    if cols_no_encontradas:
        print(f"Columnas no encontradas del diccionario: {cols_no_encontradas}")
    else: 
        print('Todas las claves del diccionario se encuentran como columnas en el dataframe.')
    
    df_copy.rename(dict_cols, axis=1, inplace=True)
    
    return df_copy

In [74]:
cols_original = df_epa_decod.columns
cols_original

Index(['CICLO', 'CCAA', 'PROV', 'NVIVI', 'NPERS', 'EDAD1', 'RELPP1', 'SEXO1',
       'PESO', 'NFORMA', 'EDADEST', 'CURSR', 'NCURSR', 'CURSNR', 'PRONA1',
       'REGNA1', 'NAC1', 'EXREGNA1', 'ANORE1'],
      dtype='object')

In [79]:
cols_cambio = [
    'Periodo de referencia (año/trimestre)', 
    'Comunidad Autónoma', 
    'Provincia', 
    'Identificador de vivienda',
    'Identificador de persona dentro del hogar', 
    'Edad', 
    'Relación con la p.r.', 
    'Sexo',
    'Peso', 
    'Nivel educativo', 
    'Edad nivel max de estudio', 
    'Formación reglada reciente', 
    'Nivel de la formación reglada', 
    'Formación no reglada reciente',
    'Provincia de nacimiento (España)',
    'Región de nacimiento (extranjero)', 
    'Nacionalidad', 
    'Región de nacionalidad extranjera', 
    'Años de residencia en España'
]

In [80]:
print('¿Es la longitud de las columnas originales igual a la longitud de las columnas por las que vamos a cambiarlas?:')

if (len(cols_original) == len(cols_cambio)) == True: 
    print('Verdadero')
else: 
    print('Falso')

# print(len(cols_original) == len(cols_cambio))

¿Es la longitud de las columnas originales igual a la longitud de las columnas por las que vamos a cambiarlas?:
Verdadero

In [81]:
dict_cols = dict(zip(cols_original, cols_cambio))
dict_cols

{'CICLO': 'Periodo de referencia (año/trimestre)',
 'CCAA': 'Comunidad Autónoma',
 'PROV': 'Provincia',
 'NVIVI': 'Identificador de vivienda',
 'NPERS': 'Identificador de persona dentro del hogar',
 'EDAD1': 'Edad',
 'RELPP1': 'Relación con la p.r.',
 'SEXO1': 'Sexo',
 'PESO': 'Peso',
 'NFORMA': 'Nivel educativo',
 'EDADEST': 'Edad nivel max de estudio',
 'CURSR': 'Formación reglada reciente',
 'NCURSR': 'Nivel de la formación reglada',
 'CURSNR': 'Formación no reglada reciente',
 'PRONA1': 'Provincia de nacimiento (España)',
 'REGNA1': 'Región de nacimiento (extranjero)',
 'NAC1': 'Nacionalidad',
 'EXREGNA1': 'Región de nacionalidad extranjera',
 'ANORE1': 'Años de residencia en España'}

In [82]:
df_epa_decod_prueba = cambio_nombre_col(df_epa_decod, dict_cols)

Todas las claves del diccionario se encuentran como columnas en el dataframe.

In [85]:
df_epa_decod_prueba.sample(3)

,Periodo de referencia (año/trimestre),Comunidad Autónoma,Provincia,Identificador de vivienda,Identificador de persona dentro del hogar,Edad,Relación con la p.r.,Sexo,Peso,Nivel educativo,Edad nivel max de estudio,Formación reglada reciente,Nivel de la formación reglada,Formación no reglada reciente,Provincia de nacimiento (España),Región de nacimiento (extranjero),Nacionalidad,Región de nacionalidad extranjera,Años de residencia en España
51370,2021T1,Castilla y León,León,24284,1,45-49,Persona de referencia (p.r.),Hombre,87.65,"Educación superior (códigos 51, 52, 61-63, 71-...",22.0,No,NaN,3.0,León,NaN,Española,NaN,NaN
577581,2022T1,Melilla,Melilla,53778,3,45-49,"Hijo/a, hijastro/a (de la p.r o pareja del mismo)",Mujer,75.16,"Educación superior (códigos 51, 52, 61-63, 71-...",23.0,No,NaN,3.0,Melilla,NaN,Española,NaN,NaN
864929,2022T4,"Navarra, Comunidad Foral de",Navarra,31939,2,+65,Cónyuge o pareja de la p.r.,Mujer,185.49,"Educación superior (códigos 51, 52, 61-63, 71-...",26.0,No,NaN,3.0,Navarra,NaN,Española,NaN,NaN